# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build Steps

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Permission can be added at job level or workflow level    
permissions:
      id-token: write
      contents: read

jobs:
  dotnet-build:
    uses: c-society-repository/gitworkflow-dotnet/.github/workflows/build.yml@main
    secrets: inherit
